---
common:
  remote_ip: "localhost"
  remote_port: 6666

  transmit_resolution: [512, 512]

  output_dir: "result"

apps:
  - { "src": "resource/aist/group/locking_ch01/gLO_sGR_c01_d13_d14_d15_mLO0_ch01.mp4", "name": "EchoApp" }
  - { "src": "resource/aist/group/locking_ch01/gLO_sGR_c02_d13_d14_d15_mLO0_ch01.mp4", "name": "EchoApp" }
  - { "src": "resource/aist/group/locking_ch01/gLO_sGR_c08_d13_d14_d15_mLO0_ch01.mp4", "name": "EchoApp" }
