---
common:
  remote_ip: "140.112.18.217"
  remote_port: 6666

  transmit_resolution: [512, 512]

  output_dir: "result"

apps:
  # Demo Purpose
  # - { "src": "0", "name": "EchoApp" }
  # - { "src": "1", "name": "EchoApp" }
  # - { "src": "2", "name": "EchoApp" }
  # Locking
  # - { "src": "resource/aist/locking_ch01/gLO_sGR_c01_d13_d14_d15_mLO0_ch01.mp4", "name": "MTMCApp" }
  # - { "src": "resource/aist/locking_ch01/gLO_sGR_c02_d13_d14_d15_mLO0_ch01.mp4", "name": "MTMCApp" }
  # - { "src": "resource/aist/locking_ch01/gLO_sGR_c08_d13_d14_d15_mLO0_ch01.mp4", "name": "MTMCApp" }
  # Popping
  # - { "src": "resource/aist/popping_ch01/gPO_sGR_c01_d10_d11_d12_mPO0_ch01.mp4", "name": "DetApp" }
  # - { "src": "resource/aist/popping_ch01/gPO_sGR_c02_d10_d11_d12_mPO0_ch01.mp4", "name": "DetApp" }
  # - { "src": "resource/aist/popping_ch01/gPO_sGR_c08_d10_d11_d12_mPO0_ch01.mp4", "name": "DetApp" }
