---
app:
  remote_ip: "localhost"
  remote_port: 6666

  font_scale: 3
  line_thickness: 10

  resolution: [1920, 1080]
  transmit_resolution: [512, 512]

  output_dir: "result"

  nrows: 2
  ncols: 2
  sources:
    - "resource/aist/group/locking_ch01/gLO_sGR_c01_d13_d14_d15_mLO0_ch01.mp4"
    - "resource/aist/group/locking_ch01/gLO_sGR_c02_d13_d14_d15_mLO0_ch01.mp4"
    - "resource/aist/group/locking_ch01/gLO_sGR_c08_d13_d14_d15_mLO0_ch01.mp4"
