---
app:
  remote_ip: "localhost"
  remote_port: 6666

  font_scale: 3
  line_thickness: 10

  resolution: [1920, 1080]
  transmit_resolution: [512, 512]

  output_dir: "result"

  nrows: 2
  ncols: 2
  sources:
    # IP Cameras
    # ==========================================================================
    - "rtsp://johnnylord:johnny860410@140.112.21.206:88/videoMain"
    - "rtsp://johnnylord:johnny860410@140.112.18.218:88/videoMain"
    - "rtsp://syno:fa906e293c722aa4717aa915e3ee5e37@140.112.18.219:554/Sms=5.unicast"
    #- "rtsp://syno:fa906e293c722aa4717aa915e3ee5e37@140.112.18.219:554/Sms=5.unicast"
    # Solo dance
    # ==========================================================================
    # - "resource/motion/straight/video1.avi"
    # - "resource/motion/straight/video2.avi"
    # Demo purpose
    # - "0"
    # - "1"
    # - "2"
    # Solo dance
    # ==========================================================================
    # - "resource/aist/solo/house_ch10/gHO_sFM_c01_d20_mHO2_ch10.mp4"
    # - "resource/aist/solo/house_ch10/gHO_sFM_c02_d20_mHO2_ch10.mp4"
    # - "resource/aist/solo/house_ch10/gHO_sFM_c08_d20_mHO2_ch10.mp4"
    # Group Dance
    # ==========================================================================
    # Locking videos
    #- "resource/aist/group/locking_ch01/gLO_sGR_c01_d13_d14_d15_mLO0_ch01.mp4"
    #- "resource/aist/group/locking_ch01/gLO_sGR_c02_d13_d14_d15_mLO0_ch01.mp4"
    #- "resource/aist/group/locking_ch01/gLO_sGR_c08_d13_d14_d15_mLO0_ch01.mp4"
    # Popping
    #- "resource/aist/group/popping_ch01/gPO_sGR_c01_d10_d11_d12_mPO0_ch01.mp4"
    #- "resource/aist/group/popping_ch01/gPO_sGR_c02_d10_d11_d12_mPO0_ch01.mp4"
    #- "resource/aist/group/popping_ch01/gPO_sGR_c08_d10_d11_d12_mPO0_ch01.mp4"
    # House
    #- "resource/aist/group/house_ch10/gHO_sGR_c01_d19_d20_d21_mHO4_ch10.mp4"
    #- "resource/aist/group/house_ch10/gHO_sGR_c02_d19_d20_d21_mHO4_ch10.mp4"
    #- "resource/aist/group/house_ch10/gHO_sGR_c08_d19_d20_d21_mHO4_ch10.mp4"
    # CMU Labratory (4)
    #- "resource/cmu_lab/4p-c0.avi"
    #- "resource/cmu_lab/4p-c1.avi"
    #- "resource/cmu_lab/4p-c2.avi"
    #- "resource/cmu_lab/4p-c3.avi"
    # CMU campus (4)
    #- "resource/cmu_campus/campus4-c0.avi"
    #- "resource/cmu_campus/campus4-c1.avi"
    #- "resource/cmu_campus/campus4-c2.avi"
